version: "3.3"

services:
  app:
    container_name: jmdkh-mltb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_FILE_URL=$CONFIG_FILE_URL
    command: bash start.sh
    restart: on-failure
    ports:
      - $MIRROR_PORT:80